# Generated by Django 5.1.3 on 2024-11-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
    ]
